version: '3.9'

services:
  db:
    image: postgres:16
    container_name: everytugrug-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: everytugrug_user
      POSTGRES_PASSWORD: 1q2w
      POSTGRES_DB: everytugrug
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
