services:
  - type: web
    name: everytugrug-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        value: Cedric123$
      - key: JWT_SECRET_KEY
        value: jwt-cedric
      - key: JWT_ACCESS_TOKEN_EXPIRES
        value: "900"
      - key: DATABASE_URL
        fromDatabase:
          name: everytugrug
          property: connectionString
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production

databases:
  - name: everytugrug
    plan: free
