services:
  - type: web
    name: everytugrug-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: Cedric123$
      - key: JWT_SECRET_KEY
        value: jwt-cedric
      - key: JWT_ACCESS_TOKEN_EXPIRES
        value: "900"
      - key: DATABASE_URL
        fromDatabase:
          name: everytugrug-db # ✅ Use the actual Render DB name
          property: postgresql://everytugrug_user:1q2w@localhost:5432/everytugrug

databases:
  - name: everytugrug-db # ✅ Must match the name above
    plan: free
