services:
  - type: web
    name: everytugrug-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: Cedric123$
      - key: JWT_SECRET_KEY
        value: jwt-cedric
      - key: JWT_ACCESS_TOKEN_EXPIRES
        value: "False"
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: bazarafff@gmail.com
      - key: MAIL_PASSWORD
        value: Reczann99!
      - key: MAIL_DEFAULT_SENDER
        value: bazarafff@gmail.com
      - key: DATABASE_URL
        fromDatabase:
          name: everytugrug-db
          property: connectionString

databases:
  - name: everytugrug-db
    plan: free
