"""imp

Revision ID: 29100a4ac0ad
Revises: 2c1f00835cab
Create Date: 2025-06-01 20:10:06.115344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29100a4ac0ad'
down_revision = '2c1f00835cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
