"""imp

Revision ID: 2c1f00835cab
Revises: 9778fb677dd9
Create Date: 2025-06-01 18:53:03.739891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c1f00835cab'
down_revision = '9778fb677dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statement_result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('txn_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('begin_balance', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('debit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('credit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('end_balance', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counterparty', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='statement_result_pkey')
    )
    # ### end Alembic commands ###
