"""Add mail alerts

Revision ID: 2cef2443395f
Revises: dddf7b314238
Create Date: 2025-05-18 01:04:50.771046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cef2443395f'
down_revision = 'dddf7b314238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=True),
    sa.Column('total_expense', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_budget_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('limit', sa.Float(), nullable=False),
    sa.Column('spent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['core_budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('phone_number')

    op.drop_table('core_budget_categories')
    op.drop_table('core_budgets')
    # ### end Alembic commands ###
